/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as yieldGuardVaultSol from "./YieldGuardVault.sol";
export type { yieldGuardVaultSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { AaveStrategy } from "./AaveStrategy";
export type { BaseStrategy } from "./BaseStrategy";
export type { MorphoStrategy } from "./MorphoStrategy";
export type { YieldGuardFactory } from "./YieldGuardFactory";
export * as factories from "./factories";
export { AaveStrategy__factory } from "./factories/AaveStrategy__factory";
export { BaseStrategy__factory } from "./factories/BaseStrategy__factory";
export type { IYieldStrategy } from "./interfaces/IYieldStrategy";
export { IYieldStrategy__factory } from "./factories/interfaces/IYieldStrategy__factory";
export type { MockERC20 } from "./mocks/MockERC20";
export { MockERC20__factory } from "./factories/mocks/MockERC20__factory";
export { MorphoStrategy__factory } from "./factories/MorphoStrategy__factory";
export { YieldGuardFactory__factory } from "./factories/YieldGuardFactory__factory";
export type { IERC20 } from "./YieldGuardVault.sol/IERC20";
export { IERC20__factory } from "./factories/YieldGuardVault.sol/IERC20__factory";
export type { YieldGuardVault } from "./YieldGuardVault.sol/YieldGuardVault";
export { YieldGuardVault__factory } from "./factories/YieldGuardVault.sol/YieldGuardVault__factory";
