/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YieldGuardFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployVault"
      | "getVaultCount"
      | "getVaults"
      | "isVaultFromFactory"
      | "owner"
      | "vaultCount"
      | "vaults"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployVault",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getVaults", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isVaultFromFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVaultFromFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace VaultDeployedEvent {
  export type InputTuple = [
    vault: AddressLike,
    name: string,
    asset: AddressLike,
    aaveStrategy: AddressLike,
    morphoStrategy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    name: string,
    asset: string,
    aaveStrategy: string,
    morphoStrategy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    vault: string;
    name: string;
    asset: string;
    aaveStrategy: string;
    morphoStrategy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldGuardFactory extends BaseContract {
  connect(runner?: ContractRunner | null): YieldGuardFactory;
  waitForDeployment(): Promise<this>;

  interface: YieldGuardFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployVault: TypedContractMethod<
    [_name: string, _asset: AddressLike, _performanceFee: BigNumberish],
    [string],
    "nonpayable"
  >;

  getVaultCount: TypedContractMethod<[], [bigint], "view">;

  getVaults: TypedContractMethod<[], [string[]], "view">;

  isVaultFromFactory: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  vaultCount: TypedContractMethod<[], [bigint], "view">;

  vaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployVault"
  ): TypedContractMethod<
    [_name: string, _asset: AddressLike, _performanceFee: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getVaultCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isVaultFromFactory"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "VaultDeployed"
  ): TypedContractEvent<
    VaultDeployedEvent.InputTuple,
    VaultDeployedEvent.OutputTuple,
    VaultDeployedEvent.OutputObject
  >;

  filters: {
    "VaultDeployed(address,string,address,address,address,uint256)": TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
    VaultDeployed: TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
  };
}
